services:
    #nginx
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    #php
    app:
        build:
            dockerfile: ./php/Dockerfile
        volumes:
            - ./app:/var/www/html
    #mysql
    db:
        image: mysql:8.0
        volumes: 
            - mysqldata:/var/lib/mysql
        ports:
            - "3306:3306"
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            #MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: docker-php


    #redis

volumes:
    mysqldata: